// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR9ilMLWM5Votd7o4rUmv_Wgr_-PUUuL4',
    appId: '1:43179496959:web:2fe24abd813786993d43ca',
    messagingSenderId: '43179496959',
    projectId: 'fitbuddy-452ce',
    authDomain: 'fitbuddy-452ce.firebaseapp.com',
    storageBucket: 'fitbuddy-452ce.firebasestorage.app',
    measurementId: 'G-GR41GG4663',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2klNMRIuEMAvA3RJwSvUaPTCQFVjSJA',
    appId: '1:43179496959:android:8054cab7e80b73c73d43ca',
    messagingSenderId: '43179496959',
    projectId: 'fitbuddy-452ce',
    storageBucket: 'fitbuddy-452ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7DoOfIHAiCRwlsaXmZB-Brpwa3BYwJ9c',
    appId: '1:43179496959:ios:3310bbb044ecaafd3d43ca',
    messagingSenderId: '43179496959',
    projectId: 'fitbuddy-452ce',
    storageBucket: 'fitbuddy-452ce.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7DoOfIHAiCRwlsaXmZB-Brpwa3BYwJ9c',
    appId: '1:43179496959:ios:3310bbb044ecaafd3d43ca',
    messagingSenderId: '43179496959',
    projectId: 'fitbuddy-452ce',
    storageBucket: 'fitbuddy-452ce.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR9ilMLWM5Votd7o4rUmv_Wgr_-PUUuL4',
    appId: '1:43179496959:web:c0240cd368a504c13d43ca',
    messagingSenderId: '43179496959',
    projectId: 'fitbuddy-452ce',
    authDomain: 'fitbuddy-452ce.firebaseapp.com',
    storageBucket: 'fitbuddy-452ce.firebasestorage.app',
    measurementId: 'G-DRD34DHVC0',
  );
}
